//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sacmaumvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdsBanner
    {
        public int AdsBannerID { get; set; }
        public string FileName { get; set; }
        public Nullable<int> AdsCategoryID { get; set; }
        public string CompanyName { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<double> Ratio { get; set; }
    
        public virtual AdsCategory AdsCategory { get; set; }
    }
}
