//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sacmaumvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer1
    {
        public int ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerNameEn { get; set; }
        public string ManufacturerImage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Content { get; set; }
        public string ContentEn { get; set; }
    }
}
