//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sacmaumvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<int> ShippingStatusID { get; set; }
        public string PaymentMethodID { get; set; }
        public Nullable<int> BillingAddressID { get; set; }
        public Nullable<int> ShippingAddressID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> DeliveryMethodsID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> CustomerAddressID { get; set; }
        public string Email { get; set; }
        public Nullable<int> PayStatusID { get; set; }
    }
}
