//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sacmaumvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int PartnerID { get; set; }
        public string PartnerName { get; set; }
        public string PartnerNameEn { get; set; }
        public string PartnerImage { get; set; }
        public string Address { get; set; }
        public string LinkWebsite { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    }
}
