//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sacmaumvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public string PaymentMethodID { get; set; }
        public string PaymentMethodName { get; set; }
        public string PaymentMethodNameEn { get; set; }
    }
}
