//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sacmaumvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoAlbumCategory
    {
        public PhotoAlbumCategory()
        {
            this.PhotoAlbums = new HashSet<PhotoAlbum>();
        }
    
        public int PhotoAlbumCategoryID { get; set; }
        public string ImageName { get; set; }
        public string PhotoAlbumCategoryName { get; set; }
        public string PhotoAlbumCategoryNameEn { get; set; }
        public Nullable<bool> IsShowOnMenu { get; set; }
        public Nullable<bool> IsShowOnHomePage { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual ICollection<PhotoAlbum> PhotoAlbums { get; set; }
    }
}
